import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Menu Altri",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar /> */}
        <main className="flex min-h-screen w-full flex-col bg-muted/40 relative">
          {children}
        </main>
      </body>
    </html>
    // </ClerkProvider>
  );
}
